### ISSUE TITLE
Add KCAL support

### ISSUE THREAD

**Issue by Angrydr0id** [Tomoms/android_kernel_essential_msm8998#1]
Hello.
I would like to know if it is possible to add kcal support in the kernel?

Thanks.

**Comment by Tomoms** [comment]
Hello, it is most likely possible. I'll look into it. If you could point me to some kernel for mata or any other msm8998 device that has got KCAL, it would be useful.

**Comment by Angrydr0id** [comment]
> Hello, it is most likely possible. I'll look into it. If you could point me to some kernel for mata or any other msm8998 device that has got KCAL, it would be useful.

Sure, ElementalX kernel includes kcal support for mata: https://github.com/flar2/mata (Updated until February 2020, Android 10) This is ElementalX kernel for Pixel 2 that is also a msm8998: https://github.com/flar2/wahoo (Updated until Septembre 2020, Android 11)
This is FrancoKernel for OnePlus 5: https://github.com/franciscofranco/OP5-5T-unified (It's old but maybe helpful)

If you need any more information or help you can count on me.
Thanks.

**Comment by Tomoms** [comment]
Kcal and Klapse are now supported!
